services:
  vault:
    privileged: true
    image: "hashicorp/vault:latest"
    restart: unless-stopped
    container_name: vault
    ports:
    - "8201:8201"
    - "443:8200"
    environment:
      VAULT_API_ADDR: "https://vault.test.lan"
      VAULT_CACERT: /vault/userconfig/tls/ca.crt
    cap_add:
    - IPC_LOCK
    volumes:
    - ./audit:/vault/audit
    - ./config:/vault/config
    - ./data:/vault/data
    - ./file:/vault/file
    - ./logs:/vault/logs
    - ./userconfig:/vault/userconfig
    - ./plugins:/vault/plugins
    # - ./certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    command: vault server -config=/vault/config/vault-config.hcl
    networks:
    - services_net

networks:
  services_net:
    driver: bridge