services:
    vault:
        image: hashicorp/vault:latest
        container_name: vault
        restart: unless-stopped
        cap_add:
            - IPC_LOCK
        ports:
            - "8200:8200"
        environment:
            VAULT_ADDR: http://127.0.0.1:8200
            VAULT_LOCAL_CONFIG: |
                {
                    "disable_mlock": true,
                    "ui": true,
                    "listener": [
                        {
                            "tcp": {
                                "address": "0.0.0.0:8200",
                                "tls_disable": 1
                            }
                        }
                    ],
                    "storage": {
                        "raft": {
                            "path": "/vault/data",
                            "node_id": "vault-1"
                        }
                    },
                    "api_addr": "http://127.0.0.1:8200",
                    "cluster_addr": "http://127.0.0.1:8201"
                }
        command: server
        volumes:
            - vault_data:/vault/data

volumes:
    vault_data:
